# Generated by Django 5.1.5 on 2025-01-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='numero_fax',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='twitter',
        ),
    ]
