from rest_framework import serializers

class AbonadoSerializer(serializers.Serializer):
    idServicio = serializers.CharField()
    filial = serializers.CharField()
    codigoAbonado = serializers.CharField()
    telefono = serializers.CharField(allow_blank=True, required=False)
    celular = serializers.CharField(allow_blank=True, required=False)
    celularDos = serializers.CharField(allow_blank=True, required=False)
    celularTres = serializers.CharField(allow_blank=True, required=False)
    documentoIdentidad = serializers.CharField()
    nombres = serializers.CharField()
    apellidos = serializers.CharField(allow_blank=True, required=False)
    departamento = serializers.CharField(allow_blank=True, required=False)
    provincia = serializers.CharField(allow_blank=True, required=False)
    distrito = serializers.CharField(allow_blank=True, required=False)
    direccion = serializers.CharField(allow_blank=True, required=False)
    deuda = serializers.FloatField()
    tipoVivienda = serializers.CharField(allow_blank=True, required=False)
    planContratado = serializers.CharField(allow_blank=True, required=False)
    plano = serializers.CharField(allow_blank=True, required=False)
    estadoServicio = serializers.CharField()
    fechaInstalacion = serializers.CharField()
    fechaUltimoCorte = serializers.CharField(allow_blank=True, required=False)
    tarifa = serializers.FloatField()
    PaqueteAdicional = serializers.CharField(allow_blank=True, required=False)
    saldoEntero = serializers.IntegerField()
    saldoDecimal = serializers.IntegerField()
    diaUltimoPago = serializers.IntegerField()
    mesUltimoPago = serializers.IntegerField()
    claseServicio = serializers.CharField()
    codigoClaseServicio = serializers.CharField()
    codCategoria = serializers.CharField()
    categoria = serializers.CharField()
    latitud = serializers.CharField(allow_blank=True, required=False)
    longitud = serializers.CharField(allow_blank=True, required=False)
    anioNacimiento = serializers.CharField(allow_blank=True, required=False)
    fechaVencimiento = serializers.CharField(allow_blank=True, required=False)
    codigoClientePago = serializers.CharField()
    correo = serializers.EmailField(allow_blank=True, required=False)
    nroOSInstalacion = serializers.CharField(allow_blank=True, required=False)
    estadoServicioInstalacion = serializers.CharField(allow_blank=True, required=False)
    fechaRegistro = serializers.CharField(allow_blank=True, required=False)
    motivoCorte = serializers.CharField(allow_blank=True, required=False)
    idFilial = serializers.IntegerField(required=False)
    IdAbonado = serializers.IntegerField(required=False)
